name: Deploy to GitHub Pages

defaults:
  run:
    working-directory: ./client
on:
  push:
    branches:
      - community-deploy

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build


      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
